In [1]:
# Import dependencies
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 400)

### Extract the crowdfunding.xlsx Data

In [2]:
# Read the data into a Pandas DataFrame
crowdfunding_info_df = pd.read_excel('Resources/crowdfunding.xlsx')
crowdfunding_info_df.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays

In [3]:
# Get a brief summary of the crowdfunding_info DataFrame.
crowdfunding_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cf_id                    1000 non-null   int64
 1   contact_id               1000 non-null   int64
 2   company_name             1000 non-null   object
 3   blurb                    1000 non-null   object
 4   goal                     1000 non-null   int64
 5   pledged                  1000 non-null   int64
 6   outcome                  1000 non-null   object
 7   backers_count            1000 non-null   int64
 8   country                  1000 non-null   object
 9   currency                 1000 non-null   object
 10  launched_at              1000 non-null   int64
 11  deadline                 1000 non-null   int64
 12  staff_pick               1000 non-null   bool
 13  spotlight                1000 non-null   bool
 14  category & sub-category  1000 non-null   object
dtypes: bool(2), int64(7), object(6)
memory usage: 103.6+ KB

### Create the Category and Subcategory DataFrames
---
**Create a Category DataFrame that has the following columns:**
* A "category_id" column that has entries going sequentially from "cat1" to "cat*n*", where *n* is the number of unique categories
* A "category" column that contains only the category titles

Export the DataFrame as a `category.csv` CSV file.

**Create a SubCategory DataFrame that has the following columns:**
* A "subcategory_id" column that has entries going sequentially from "subcat1" to "subcat*n*", where *n* is the number of unique subcategories
* A "subcategory" column that contains only the subcategory titles

Export the DataFrame as a `subcategory.csv` CSV file.

In [4]:
# Get the crowdfunding_info_df columns.
columns = crowdfunding_info_df.columns
columns

Index(['cf_id', 'contact_id', 'company_name', 'blurb', 'goal', 'pledged',
       'outcome', 'backers_count', 'country', 'currency', 'launched_at',
       'deadline', 'staff_pick', 'spotlight', 'category & sub-category'],
      dtype='object')

In [5]:
# Assign the category and subcategory values to category and subcategory columns.

# split the 'category & sub-category' columns with the '/' symbol
categories_raw_df = crowdfunding_info_df['category & sub-category'].str.split('/', expand=True)

# rename columns
categories_raw_df = categories_raw_df.rename(columns={0: 'category', 1: 'subcategory'})

# concatenate the columns
crowdfunding_info_df = pd.concat([crowdfunding_info_df, categories_raw_df], axis=1)

crowdfunding_info_df.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [6]:
# Get the unique categories and subcategories in separate lists.
categories = list(crowdfunding_info_df['category'].unique())
subcategories = list(crowdfunding_info_df['subcategory'].unique())

print(categories)
print(subcategories)

['food', 'music', 'technology', 'theater', 'film & video', 'publishing', 'games', 'photography', 'journalism']
['food trucks', 'rock', 'web', 'plays', 'documentary', 'electric music', 'drama', 'indie rock', 'wearables', 'nonfiction', 'animation', 'video games', 'shorts', 'fiction', 'photography books', 'radio & podcasts', 'metal', 'jazz', 'translations', 'television', 'mobile games', 'world music', 'science fiction', 'audio']

In [7]:
# Get the number of distinct values in the categories and subcategories lists.
print(len(categories))
print(len(subcategories))

9
24

In [8]:
# Create numpy arrays from 1-9 for the categories and 1-24 for the subcategories.
category_ids = np.arange(1, 10)
subcategory_ids = np.arange(1, 25)

print(category_ids)
print(subcategory_ids)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

In [9]:
# Use a list comprehension to add "cat" to each category_id. 
cat_ids = [f"cat{id}" for id in category_ids]

# Use a list comprehension to add "subcat" to each subcategory_id.    
scat_ids = [f"subcat{id}" for id in subcategory_ids]
    
print(cat_ids)
print(scat_ids)

['cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8', 'cat9']
['subcat1', 'subcat2', 'subcat3', 'subcat4', 'subcat5', 'subcat6', 'subcat7', 'subcat8', 'subcat9', 'subcat10', 'subcat11', 'subcat12', 'subcat13', 'subcat14', 'subcat15', 'subcat16', 'subcat17', 'subcat18', 'subcat19', 'subcat20', 'subcat21', 'subcat22', 'subcat23', 'subcat24']

In [10]:
# Create a category DataFrame with the category_id array as the category_id and categories list as the category name.
category_df = pd.DataFrame(zip(cat_ids, categories)). \
                rename(columns={0: 'category_id', 1: 'category'})

# Create a category DataFrame with the subcategory_id array as the subcategory_id and subcategories list as the subcategory name. 
subcategory_df = pd.DataFrame(zip(scat_ids, subcategories)). \
                rename(columns={0: 'subcategory_id', 1: 'subcategory'})

In [11]:
category_df

  category_id      category
0        cat1          food
1        cat2         music
2        cat3    technology
3        cat4       theater
4        cat5  film & video
5        cat6    publishing
6        cat7         games
7        cat8   photography
8        cat9    journalism

In [12]:
subcategory_df

   subcategory_id        subcategory
0         subcat1        food trucks
1         subcat2               rock
2         subcat3                web
3         subcat4              plays
4         subcat5        documentary
5         subcat6     electric music
6         subcat7              drama
7         subcat8         indie rock
8         subcat9          wearables
9        subcat10         nonfiction
10       subcat11          animation
11       subcat12        video games
12       subcat13             shorts
13       subcat14            fiction
14       subcat15  photography books
15       subcat16   radio & podcasts
16       subcat17              metal
17       subcat18               jazz
18       subcat19       translations
19       subcat20         television
20       subcat21       mobile games
21       subcat22        world music
22       subcat23    science fiction
23       subcat24              audio

In [13]:
# Export categories_df and subcategories_df as CSV files.
category_df.to_csv("Resources/category.csv", index=False)

subcategory_df.to_csv("Resources/subcategory.csv", index=False)

### Campaign DataFrame
----
**Create a Campaign DataFrame that has the following columns:**
- The "cf_id" column.
- The "contact_id" column.
- The “company_name” column.
- The "blurb" column is renamed as "description."
- The "goal" column.
- The "goal" column is converted to a `float` datatype.
- The "pledged" column is converted to a `float` datatype. 
- The "backers_count" column. 
- The "country" column.
- The "currency" column.
- The "launched_at" column is renamed as "launch_date" and converted to a datetime format. 
- The "deadline" column is renamed as "end_date" and converted to a datetime format.
- The "category_id" with the unique number matching the “category_id” from the category DataFrame. 
- The "subcategory_id" with the unique number matching the “subcategory_id” from the subcategory DataFrame.
- And, create a column that contains the unique four-digit contact ID number from the `contact.xlsx` file.
 

Then export the DataFrame as a `campaign.csv` CSV file.

In [14]:
# Create a copy of the crowdfunding_info_df DataFrame name campaign_df. 
campaign_df = crowdfunding_info_df.copy()
campaign_df.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [15]:
# Rename the blurb, launched_at, and deadline columns.
campaign_df = campaign_df.rename(columns={'blurb': 'description', 'launched_at': 'launched_date', 'deadline': 'end_date'})
campaign_df.head()

,cf_id,contact_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [16]:
campaign_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cf_id                    1000 non-null   int64
 1   contact_id               1000 non-null   int64
 2   company_name             1000 non-null   object
 3   description              1000 non-null   object
 4   goal                     1000 non-null   int64
 5   pledged                  1000 non-null   int64
 6   outcome                  1000 non-null   object
 7   backers_count            1000 non-null   int64
 8   country                  1000 non-null   object
 9   currency                 1000 non-null   object
 10  launched_date            1000 non-null   int64
 11  end_date                 1000 non-null   int64
 12  staff_pick               1000 non-null   bool
 13  spotlight                1000 non-null   bool
 14  category & sub-category  1000 non-null   object
 15  category                 1000 non-null   object
 16  subcategory              1000 non-null   object
dtypes: bool(2), int64(7), object(8)
memory usage: 119.3+ KB

In [17]:
# Convert the goal and pledged columns to a `float` data type.
campaign_df['goal'] = campaign_df['goal'].astype(float)
campaign_df['pledged'] = campaign_df['pledged'].astype(float)

campaign_df.head()

,cf_id,contact_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [18]:
# Check the datatypes
campaign_df.dtypes

cf_id                        int64
contact_id                   int64
company_name                object
description                 object
goal                       float64
pledged                    float64
outcome                     object
backers_count                int64
country                     object
currency                    object
launched_date                int64
end_date                     int64
staff_pick                    bool
spotlight                     bool
category & sub-category     object
category                    object
subcategory                 object
dtype: object

In [19]:
# Format the launched_date and end_date columns to datetime format
from datetime import datetime as dt
campaign_df['launched_date'] = pd.to_datetime(campaign_df['launched_date'], unit='s').dt.date
campaign_df['end_date'] = pd.to_datetime(campaign_df['end_date'], unit='s').dt.date

campaign_df.head()

,cf_id,contact_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,2020-02-13,2021-03-01,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,2021-01-25,2021-05-25,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,2020-12-17,2021-12-30,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,2021-10-21,2022-01-17,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,2020-12-21,2021-08-23,False,False,theater/plays,theater,plays

In [20]:
# Merge the campaign_df with the category_df on the "category" column and 
# the subcategory_df on the "subcategory" column.
campaign_merged_df = campaign_df.merge(category_df, on='category', how='left')
campaign_merged_df = campaign_merged_df.merge(subcategory_df, on='subcategory', how='left')

campaign_merged_df.tail(10)

,cf_id,contact_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory,category_id,subcategory_id
990,1561,5500,Ortiz-Roberts,Devolved foreground customer loyalty,7800.0,6839.0,failed,64,US,USD,2021-06-09,2021-06-18,False,True,film & video/drama,film & video,drama,cat5,subcat7
991,2632,3494,Ramirez LLC,Reduced reciprocal focus group,9800.0,11091.0,successful,241,US,USD,2020-12-09,2021-05-26,False,True,music/rock,music,rock,cat2,subcat2
992,439,3924,Morrow Inc,Networked global migration,3100.0,13223.0,successful,132,US,USD,2020-06-14,2021-02-09,False,True,film & video/drama,film & video,drama,cat5,subcat7
993,461,3521,Erickson-Rogers,De-engineered even-keeled definition,9800.0,7608.0,canceled,75,IT,EUR,2021-07-03,2021-07-08,False,True,photography/photography books,photography,photography books,cat8,subcat15
994,1419,5262,"Leach, Rich and Price",Implemented bi-directional flexibility,141100.0,74073.0,failed,842,US,USD,2021-11-15,2021-12-07,False,True,publishing/translations,publishing,translations,cat6,subcat19
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300.0,153216.0,successful,2043,US,USD,2020-12-29,2021-05-30,False,True,food/food trucks,food,food trucks,cat1,subcat1
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600.0,4814.0,failed,112,US,USD,2021-10-15,2021-11-30,False,False,theater/plays,theater,plays,cat4,subcat4
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600.0,4603.0,canceled,139,IT,EUR,2021-11-06,2021-12-10,False,False,theater/plays,theater,plays,cat4,subcat4
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600.0,37823.0,failed,374,US,USD,2020-10-08,2021-04-11,False,True,music/indie rock,music,indie rock,cat2,subcat8
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100.0,62819.0,canceled,1122,US,USD,2020-12-30,2021-08-18,False,False,food/food trucks,food,food trucks,cat1,subcat1

In [21]:
# Drop unwanted columns
drop_list = ['staff_pick', 'spotlight', 'category & sub-category', 'category', 'subcategory']
campaign_cleaned = campaign_merged_df.drop(columns=drop_list)

campaign_cleaned.head()

,cf_id,contact_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,category_id,subcategory_id
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,2020-02-13,2021-03-01,cat1,subcat1
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,2021-01-25,2021-05-25,cat2,subcat2
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,2020-12-17,2021-12-30,cat3,subcat3
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,2021-10-21,2022-01-17,cat2,subcat2
4,1365,2199,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,2020-12-21,2021-08-23,cat4,subcat4

In [22]:
# Export the DataFrame as a CSV file. 
campaign_cleaned.to_csv("Resources/campaign.csv", index=False)

### Extract the contacts.xlsx Data.

In [23]:
# Read the data into a Pandas DataFrame. Use the `header=3` parameter when reading in the data.
contact_info_df = pd.read_excel('Resources/contacts.xlsx', header=3)
contact_info_df.head()

                                                                                contact_info
0   {"contact_id": 4661, "name": "Cecilia Velasco", "email": "cecilia.velasco@rodrigues.fr"}
1          {"contact_id": 3765, "name": "Mariana Ellis", "email": "mariana.ellis@rossi.org"}
2            {"contact_id": 4187, "name": "Sofie Woods", "email": "sofie.woods@riviere.com"}
3  {"contact_id": 4941, "name": "Jeanette Iannotti", "email": "jeanette.iannotti@yahoo.com"}
4        {"contact_id": 2199, "name": "Samuel Sorgatz", "email": "samuel.sorgatz@gmail.com"}

### Create the Contacts DataFrame 
---
**Create a Contacts DataFrame that has the following columns:**
- A column named "contact_id"  that contains the unique number of the contact person.
- A column named "first_name" that contains the first name of the contact person.
- A column named "last_name" that contains the first name of the contact person.
- A column named "email" that contains the email address of the contact person

Then export the DataFrame as a `contacts.csv` CSV file.

### Option 1: Use Pandas to create the contacts DataFrame.

In [24]:
# Iterate through the contact_info_df and convert each row to a dictionary.
import json
from pprint import pprint
dict_values = []

for index, row in contact_info_df.iterrows():
    dict_values.append(json.loads(dict(row)['contact_info']))

# Print out the list of values for each row.
pprint(dict_values)

[{'contact_id': 4661,
  'email': 'cecilia.velasco@rodrigues.fr',
  'name': 'Cecilia Velasco'},
 {'contact_id': 3765,
  'email': 'mariana.ellis@rossi.org',
  'name': 'Mariana Ellis'},
 {'contact_id': 4187,
  'email': 'sofie.woods@riviere.com',
  'name': 'Sofie Woods'},
 {'contact_id': 4941,
  'email': 'jeanette.iannotti@yahoo.com',
  'name': 'Jeanette Iannotti'},
 {'contact_id': 2199,
  'email': 'samuel.sorgatz@gmail.com',
  'name': 'Samuel Sorgatz'},
 {'contact_id': 5650,
  'email': 'socorro.luna@hotmail.com',
  'name': 'Socorro Luna'},
 {'contact_id': 5889,
  'email': 'carolina.murray@knight.com',
  'name': 'Carolina Murray'},
 {'contact_id': 4842, 'email': 'kayla.moon@yahoo.de', 'name': 'Kayla Moon'},
 {'contact_id': 3280,
  'email': 'ariadna.geisel@rangel.com',
  'name': 'Ariadna Geisel'},
 {'contact_id': 5468,
  'email': 'danielle.ladeck@scalfaro.net',
  'name': 'Danielle Ladeck'},
 {'contact_id': 3064,
  'email': 'tatiana.thompson@hunt.net',
  'name': 'Tatiana Thompson'},
 {'contact_id': 4904,
  'email': 'caleb.benavides@rubio.com',
  'name': 'Caleb Benavides'},
 {'contact_id': 1299, 'email': 'sandra.hardy@web.de', 'name': 'Sandra Hardy'},
 {'contact_id': 5602,
  'email': 'lotti.morris@yahoo.co.uk',
  'name': 'Lotti Morris'},
 {'contact_id': 5753,
  'email': 'reinhilde.white@voila.fr',
  'name': 'Reinhilde White'},
 {'contact_id': 4495,
  'email': 'kerry.patel@hutchinson.com',
  'name': 'Kerry Patel'},
 {'contact_id': 4269,
  'email': 'sophie.antoine@andersen.com',
  'name': 'Sophie Antoine'},
 {'contact_id': 2226, 'email': 'martha.girard@web.de', 'name': 'Martha Girard'},
 {'contact_id': 1558,
  'email': 'stephanie.king@cervantes.com',
  'name': 'Stephanie King'},
 {'contact_id': 2307,
  'email': 'amanda.palmer@didier.fr',
  'name': 'Amanda Palmer'},
 {'contact_id': 2900, 'email': 'lina.alcala@vespa.net', 'name': 'Lina Alcala'},
 {'contact_id': 5695,
  'email': 'itzel.murphy@muelichen.de',
  'name': 'Itzel Murphy'},
 {'contact_id': 5708,
  'email': 'filippo.parry@live.com',
  'name': 'Filippo Parry'},
 {'contact_id': 1663,
  'email': 'katelyn.cole@fiebig.com',
  'name': 'Katelyn Cole'},
 {'contact_id': 3605, 'email': 'brian.novak@ford.net', 'name': 'Brian Novak'},
 {'contact_id': 4678, 'email': 'cilly.gay@callegaro.it', 'name': 'Cilly Gay'},
 {'contact_id': 2251,
  'email': 'yolanda.snyder@gmx.de',
  'name': 'Yolanda Snyder'},
 {'contact_id': 6202,
  'email': 'evelin.odonnell@ibarra.net',
  'name': 'Evelin Odonnell'},
 {'contact_id': 3715,
  'email': 'ingeborg.alba@hotmail.com',
  'name': 'Ingeborg Alba'},
 {'contact_id': 4242,
  'email': 'marina.madrid@galarza-alba.com',
  'name': 'Marina Madrid'},
 {'contact_id': 4326,
  'email': 'sheila.goodwin@yahoo.com',
  'name': 'Sheila Goodwin'},
 {'contact_id': 5560,
  'email': 'valeria.rich@turchetta-mondadori.it',
  'name': 'Valeria Rich'},
 {'contact_id': 4002,
  'email': 'dustin.camacho@rhodes.org.au',
  'name': 'Dustin Camacho'},
 {'contact_id': 3813,
  'email': 'amalia.marenzio@grupo.com',
  'name': 'Amalia Marenzio'},
 {'contact_id': 5336, 'email': 'gian.long@hotmail.com', 'name': 'Gian Long'},
 {'contact_id': 4994,
  'email': 'stewart.hunt@anderson-vargas.biz',
  'name': 'Stewart Hunt'},
 {'contact_id': 1471, 'email': 'greca.ruiz@carr.co.uk', 'name': 'Greca Ruiz'},
 {'contact_id': 4482,
  'email': 'gerald.olivera@outlook.com',
  'name': 'Gerald Olivera'},
 {'contact_id': 3241,
  'email': 'jaqueline.wallace@gmail.com',
  'name': 'Jaqueline Wallace'},
 {'contact_id': 3477, 'email': 'john.lane@gregoire.fr', 'name': 'John Lane'},
 {'contact_id': 2265, 'email': 'pero.joly@bernard.net', 'name': 'Pero Joly'},
 {'contact_id': 5911, 'email': 'chad.turner@gmail.com', 'name': 'Chad Turner'},
 {'contact_id': 2288,
  'email': 'adam.zavala@guichard.fr',
  'name': 'Adam Zavala'},
 {'contact_id': 4064,
  'email': 'tyler.rivera@guajardo-ozuna.com',
  'name': 'Tyler Rivera'},
 {'contact_id': 1294,
  'email': 'jens.graham@jones-buckley.com',
  'name': 'Jens Graham'},
 {'contact_id': 5008,
  'email': 'virginia.caetani@sosa.biz',
  'name': 'Virginia Caetani'},
 {'contact_id': 3604,
  'email': 'martino.wagner@laposte.net',
  'name': 'Martino Wagner'},
 {'contact_id': 3263,
  'email': 'martin.meyer@davis.co.uk',
  'name': 'Martin Meyer'},
 {'contact_id': 5631,
  'email': 'marguerite.walls@martinez.fr',
  'name': 'Marguerite Walls'},
 {'contact_id': 2851, 'email': 'peter.vogt@yahoo.com', 'name': 'Peter Vogt'},
 {'contact_id': 3714,
  'email': 'nicholas.christian@hotmail.de',
  'name': 'Nicholas Christian'},
 {'contact_id': 1664,
  'email': 'susi.steinberg@preiss.com',
  'name': 'Susi Steinberg'},
 {'contact_id': 5027,
  'email': 'tammy.ramazzotti@gmail.com',
  'name': 'Tammy Ramazzotti'},
 {'contact_id': 3070,
  'email': 'abdul.thomas@vasari.com',
  'name': 'Abdul Thomas'},
 {'contact_id': 4248,
  'email': 'justin.luxardo@googlemail.com',
  'name': 'Justin Luxardo'},
 {'contact_id': 2034,
  'email': 'antonio.gibson@faust.net',
  'name': 'Antonio Gibson'},
 {'contact_id': 4085,
  'email': 'jeremy.gomez@oconnor.org',
  'name': 'Jeremy Gomez'},
 {'contact_id': 3569,
  'email': 'raymond.solorzano@gmail.com',
  'name': 'Raymond Solorzano'},
 {'contact_id': 3889,
  'email': 'flora.harris@hotmail.com.au',
  'name': 'Flora Harris'},
 {'contact_id': 3136, 'email': 'cheryl.boyd@segni.it', 'name': 'Cheryl Boyd'},
 {'contact_id': 2103, 'email': 'rhys.leiva@gmx.de', 'name': 'Rhys Leiva'},
 {'contact_id': 2329,
  'email': 'mariano.prieto@vodafone.it',
  'name': 'Mariano Prieto'},
 {'contact_id': 3325,
  'email': 'laurie.fibonacci@gmail.com',
  'name': 'Laurie Fibonacci'},
 {'contact_id': 3131,
  'email': 'david.rudolph@nelson.com',
  'name': 'David Rudolph'},
 {'contact_id': 4995, 'email': 'bryan.ross@yahoo.com', 'name': 'Bryan Ross'},
 {'contact_id': 3631,
  'email': 'ubaldo.brown@philippe.com',
  'name': 'Ubaldo Brown'},
 {'contact_id': 5373,
  'email': 'clelia.faulkner@hotmail.com',
  'name': 'Clelia Faulkner'},
 {'contact_id': 3126,
  'email': 'sara.erickson@yahoo.de',
  'name': 'Sara Erickson'},
 {'contact_id': 2194,
  'email': 'rupert.valle@filogamo.it',
  'name': 'Rupert Valle'},
 {'contact_id': 2906,
  'email': 'puccio.kitzmann@yahoo.com',
  'name': 'Puccio Kitzmann'},
 {'contact_id': 2611,
  'email': 'thomas.hutchinson@gmx.de',
  'name': 'Thomas Hutchinson'},
 {'contact_id': 2374,
  'email': 'abelardo.castro@gmail.com',
  'name': 'Abelardo Castro'},
 {'contact_id': 3254,
  'email': 'greco.walker@yahoo.com',
  'name': 'Greco Walker'},
 {'contact_id': 3571,
  'email': 'miranda.lacombe@longoria-vanegas.net',
  'name': 'Miranda Lacombe'},
 {'contact_id': 2812,
  'email': 'diana.schuchhardt@libero.it',
  'name': 'Diana Schuchhardt'},
 {'contact_id': 3961,
  'email': 'stacey.knox@corporacin.com',
  'name': 'Stacey Knox'},
 {'contact_id': 3872, 'email': 'glen.faivre@yahoo.com', 'name': 'Glen Faivre'},
 {'contact_id': 4736,
  'email': 'andrew.torres@ruiz-torres.org',
  'name': 'Andrew Torres'},
 {'contact_id': 5119,
  'email': 'denny.fritz@despacho.biz',
  'name': 'Denny Fritz'},
 {'contact_id': 5725,
  'email': 'martyn.caldera@hotmail.co.uk',
  'name': 'Martyn Caldera'},
 {'contact_id': 4037,
  'email': 'abigail.foster@taylor.net',
  'name': 'Abigail Foster'},
 {'contact_id': 2109,
  'email': 'anthony.hauffer@tlustek.org',
  'name': 'Anthony Hauffer'},
 {'contact_id': 3283,
  'email': 'roger.gerlach@may-mitchell.co.uk',
  'name': 'Roger Gerlach'},
 {'contact_id': 6181,
  'email': 'christopher.poirier@hotmail.com',
  'name': 'Christopher Poirier'},
 {'contact_id': 3251,
  'email': 'branka.traore@jacobi.com',
  'name': 'Branka Traore'},
 {'contact_id': 3443,
  'email': 'briana.etienne@bishop-coates.com',
  'name': 'Briana Etienne'},
 {'contact_id': 2988,
  'email': 'brandon.olson@prince-moreno.net',
  'name': 'Brandon Olson'},
 {'contact_id': 1673,
  'email': 'celia.ungaretti@fox.com',
  'name': 'Celia Ungaretti'},
 {'contact_id': 2085,
  'email': 'barbara.guibert@casares-sanches.com',
  'name': 'Barbara Guibert'},
 {'contact_id': 1672,
  'email': 'daniela.bell@vollbrecht.org',
  'name': 'Daniela Bell'},
 {'contact_id': 4426,
  'email': 'phyllis.gurule@rodriguez-pham.com',
  'name': 'Phyllis Gurule'},
 {'contact_id': 3211,
  'email': 'alejandra.joseph@escalante-abrego.biz',
  'name': 'Alejandra Joseph'},
 {'contact_id': 3190,
  'email': 'giulio.bohlander@dbmail.com',
  'name': 'Giulio Bohlander'},
 {'contact_id': 2081, 'email': 'amber.weller@toso.eu', 'name': 'Amber Weller'},
 {'contact_id': 3185,
  'email': 'mary.etzold@conrad-harrison.com',
  'name': 'Mary Etzold'},
 {'contact_id': 5044, 'email': 'amy.georges@raedel.de', 'name': 'Amy Georges'},
 {'contact_id': 1883,
  'email': 'jennifer.giraud@yahoo.com',
  'name': 'Jennifer Giraud'},
 {'contact_id': 2067,
  'email': 'rosie.peltier@voila.fr',
  'name': 'Rosie Peltier'},
 {'contact_id': 4604,
  'email': 'oreste.ward@proyectos.com',
  'name': 'Oreste Ward'},
 {'contact_id': 3203, 'email': 'luis.edwards@live.com', 'name': 'Luis Edwards'},
 {'contact_id': 5758,
  'email': 'fiona.griffiths@curatoli-verdone.it',
  'name': 'Fiona Griffiths'},
 {'contact_id': 5755, 'email': 'sally.raya@tarchetti.it', 'name': 'Sally Raya'},
 {'contact_id': 5150,
  'email': 'carolyn.charpentier@hotmail.de',
  'name': 'Carolyn Charpentier'},
 {'contact_id': 4181,
  'email': 'nathalie.alvarez@live.com',
  'name': 'Nathalie Alvarez'},
 {'contact_id': 3006,
  'email': 'abril.lowery@novak.net',
  'name': 'Abril Lowery'},
 {'contact_id': 4865,
  'email': 'ottone.sullivan@hussain-kaur.com',
  'name': 'Ottone Sullivan'},
 {'contact_id': 2862,
  'email': 'esmeralda.sollima@visintini.it',
  'name': 'Esmeralda Sollima'},
 {'contact_id': 6070,
  'email': 'silvia.gierschner@tele2.it',
  'name': 'Silvia Gierschner'},
 {'contact_id': 5300,
  'email': 'kyle.cunningham@voila.fr',
  'name': 'Kyle Cunningham'},
 {'contact_id': 3486,
  'email': 'anel.carpentier@klein-joseph.org',
  'name': 'Anel Carpentier'},
 {'contact_id': 5989, 'email': 'sarah.davis@david.com', 'name': 'Sarah Davis'},
 {'contact_id': 2849, 'email': 'luke.klein@hotmail.com', 'name': 'Luke Klein'},
 {'contact_id': 1612,
  'email': 'gudrun.mueller@dillon-fuller.info',
  'name': 'Gudrun Mueller'},
 {'contact_id': 3307,
  'email': 'melissa.canali@libero.it',
  'name': 'Melissa Canali'},
 {'contact_id': 5288,
  'email': 'gabrielle.ayala@hotmail.com',
  'name': 'Gabrielle Ayala'},
 {'contact_id': 6026,
  'email': 'laura.buckley@ryan.org',
  'name': 'Laura Buckley'},
 {'contact_id': 2212,
  'email': 'wilfrido.lorch@leclerc.fr',
  'name': 'Wilfrido Lorch'},
 {'contact_id': 4591,
  'email': 'robert.bruder@manzoni.com',
  'name': 'Robert Bruder'},
 {'contact_id': 2771,
  'email': 'phillip.soliz@outlook.com',
  'name': 'Phillip Soliz'},
 {'contact_id': 5682, 'email': 'alex.smith@fournier.fr', 'name': 'Alex Smith'},
 {'contact_id': 5368,
  'email': 'jessica.martinez@salieri.com',
  'name': 'Jessica Martinez'},
 {'contact_id': 3706,
  'email': 'kelly.carter@hotmail.com.au',
  'name': 'Kelly Carter'},
 {'contact_id': 4034, 'email': 'ahmad.sosa@gmail.com', 'name': 'Ahmad Sosa'},
 {'contact_id': 3209,
  'email': 'toralf.iglesias@borrego.com',
  'name': 'Toralf Iglesias'},
 {'contact_id': 2384,
  'email': 'irene.anichini@yahoo.com',
  'name': 'Irene Anichini'},
 {'contact_id': 3074,
  'email': 'alicia.cainero@yahoo.com',
  'name': 'Alicia Cainero'},
 {'contact_id': 2031, 'email': 'tracey.laboy@bell.biz', 'name': 'Tracey Laboy'},
 {'contact_id': 5873,
  'email': 'donald.reynaud@green.edu.au',
  'name': 'Donald Reynaud'},
 {'contact_id': 5501,
  'email': 'venancio.stadelmann@gmx.de',
  'name': 'Venancio Stadelmann'},
 {'contact_id': 3489,
  'email': 'seth.olivier@yahoo.com',
  'name': 'Seth Olivier'},
 {'contact_id': 4210, 'email': 'dennis.boaga@gmx.de', 'name': 'Dennis Boaga'},
 {'contact_id': 6151,
  'email': 'pedro.wilson@outlook.com',
  'name': 'Pedro Wilson'},
 {'contact_id': 6047,
  'email': 'roland.weihmann@gmail.com',
  'name': 'Roland Weihmann'},
 {'contact_id': 5445,
  'email': 'hector.morrison@web.de',
  'name': 'Hector Morrison'},
 {'contact_id': 5493,
  'email': 'evangelos.peters@sanchez.net',
  'name': 'Evangelos Peters'},
 {'contact_id': 6036,
  'email': 'gerardo.hamilton@libero.it',
  'name': 'Gerardo Hamilton'},
 {'contact_id': 2368,
  'email': 'meta.cuzzocrea@howard-jensen.org',
  'name': 'Meta Cuzzocrea'},
 {'contact_id': 1501, 'email': 'alma.raymond@tin.it', 'name': 'Alma Raymond'},
 {'contact_id': 4351,
  'email': 'kathleen.solimena@wallace.biz',
  'name': 'Kathleen Solimena'},
 {'contact_id': 3096,
  'email': 'zacharie.cordier@gmail.com',
  'name': 'Zacharie Cordier'},
 {'contact_id': 6162, 'email': 'riza.techer@yahoo.com', 'name': 'Riza Techer'},
 {'contact_id': 1433,
  'email': 'enrique.guillen@hotmail.co.uk',
  'name': 'Enrique Guillen'},
 {'contact_id': 2720,
  'email': 'tristan.weeks@pena.com',
  'name': 'Tristan Weeks'},
 {'contact_id': 5251,
  'email': 'natalie.lerma@boucher.com',
  'name': 'Natalie Lerma'},
 {'contact_id': 1797,
  'email': 'rodney.hamon@hotmail.com',
  'name': 'Rodney Hamon'},
 {'contact_id': 1656,
  'email': 'adalberto.lombardo@sfr.fr',
  'name': 'Adalberto Lombardo'},
 {'contact_id': 1346,
  'email': 'florencia.querini@gmail.com',
  'name': 'Florencia Querini'},
 {'contact_id': 2989, 'email': 'liam.rolland@yahoo.fr', 'name': 'Liam Rolland'},
 {'contact_id': 5629, 'email': 'ian.kelly@reeves.com.au', 'name': 'Ian Kelly'},
 {'contact_id': 3456, 'email': 'mehdi.todd@web.de', 'name': 'Mehdi Todd'},
 {'contact_id': 3229,
  'email': 'rembrandt.liguori@davis.org',
  'name': 'Rembrandt Liguori'},
 {'contact_id': 2277,
  'email': 'irmi.schweitzer@ozuna.com',
  'name': 'Irmi Schweitzer'},
 {'contact_id': 1276,
  'email': 'gioffre.stein@hotmail.com.au',
  'name': 'Gioffre Stein'},
 {'contact_id': 3694,
  'email': 'frida.villarreal@hotmail.de',
  'name': 'Frida Villarreal'},
 {'contact_id': 2260,
  'email': 'steffen.mangold@paul.net',
  'name': 'Steffen Mangold'},
 {'contact_id': 5374, 'email': 'elias.marin@herve.net', 'name': 'Elias Marin'},
 {'contact_id': 4420,
  'email': 'roman.gonzalez@anderson.net',
  'name': 'Roman Gonzalez'},
 {'contact_id': 3849,
  'email': 'reina.middleton@hotmail.com',
  'name': 'Reina Middleton'},
 {'contact_id': 1638,
  'email': 'sandro.moran@hotmail.de',
  'name': 'Sandro Moran'},
 {'contact_id': 5230,
  'email': 'gebhard.thanel@gmail.com',
  'name': 'Gebhard Thanel'},
 {'contact_id': 1763,
  'email': 'antonino.bolander@gmail.com',
  'name': 'Antonino Bolander'},
 {'contact_id': 4323,
  'email': 'karl.trevisani@anguissola.it',
  'name': 'Karl Trevisani'},
 {'contact_id': 5256,
  'email': 'silvester.brookes@franco.org',
  'name': 'Silvester Brookes'},
 {'contact_id': 4836, 'email': 'octavio.pratt@web.de', 'name': 'Octavio Pratt'},
 {'contact_id': 5981,
  'email': 'rebecca.greer@hotmail.com',
  'name': 'Rebecca Greer'},
 {'contact_id': 1463,
  'email': 'pierina.gaggini@free.fr',
  'name': 'Pierina Gaggini'},
 {'contact_id': 4577,
  'email': 'robin.schleich@rogers-barrera.biz',
  'name': 'Robin Schleich'},
 {'contact_id': 4951,
  'email': 'sergio.abbott@moore.net.au',
  'name': 'Sergio Abbott'},
 {'contact_id': 3567,
  'email': 'gilberto.evans@salcedo-archuleta.net',
  'name': 'Gilberto Evans'},
 {'contact_id': 5475,
  'email': 'james.elliott@gmail.com',
  'name': 'James Elliott'},
 {'contact_id': 2114,
  'email': 'timoteo.bolnbach@laboratorios.com',
  'name': 'Timoteo Bolnbach'},
 {'contact_id': 5216,
  'email': 'tonino.stanley@hotmail.com',
  'name': 'Tonino Stanley'},
 {'contact_id': 1665,
  'email': 'margaretha.murialdo@meunier.com',
  'name': 'Margaretha Murialdo'},
 {'contact_id': 6051,
  'email': 'bianca.drubin@libero.it',
  'name': 'Bianca Drubin'},
 {'contact_id': 3983,
  'email': 'kaylee.hoffmann@poulain.com',
  'name': 'Kaylee Hoffmann'},
 {'contact_id': 2966,
  'email': 'teresa.vecellio@yahoo.com',
  'name': 'Teresa Vecellio'},
 {'contact_id': 4478,
  'email': 'emine.tacchini@dbmail.com',
  'name': 'Emine Tacchini'},
 {'contact_id': 4238, 'email': 'dawn.cortez@gmail.com', 'name': 'Dawn Cortez'},
 {'contact_id': 4404,
  'email': 'emily.cundari@clark.com.au',
  'name': 'Emily Cundari'},
 {'contact_id': 5666,
  'email': 'eleanor.hall@hotmail.com',
  'name': 'Eleanor Hall'},
 {'contact_id': 3691,
  'email': 'monique.delgadillo@hotmail.co.uk',
  'name': 'Monique Delgadillo'},
 {'contact_id': 2703,
  'email': 'arnaude.warner@gmail.com',
  'name': 'Arnaude Warner'},
 {'contact_id': 4253, 'email': 'jason.howell@gmx.de', 'name': 'Jason Howell'},
 {'contact_id': 5652,
  'email': 'nicole.mccullough@hall.com',
  'name': 'Nicole Mccullough'},
 {'contact_id': 3279,
  'email': 'rosmarie.esquibel@bouygtel.fr',
  'name': 'Rosmarie Esquibel'},
 {'contact_id': 3233,
  'email': 'leonor.ferreira@gmail.com',
  'name': 'Leonor Ferreira'},
 {'contact_id': 3017, 'email': 'brett.jones@alice.it', 'name': 'Brett Jones'},
 {'contact_id': 3482, 'email': 'nino.bien@gmail.com', 'name': 'Nino Bien'},
 {'contact_id': 2166, 'email': 'jemma.tate@hotmail.de', 'name': 'Jemma Tate'},
 {'contact_id': 4146, 'email': 'denis.rogers@poste.it', 'name': 'Denis Rogers'},
 {'contact_id': 2651, 'email': 'vanesa.khan@voila.fr', 'name': 'Vanesa Khan'},
 {'contact_id': 1409,
  'email': 'victoria.ojeda@doehn.com',
  'name': 'Victoria Ojeda'},
 {'contact_id': 3717,
  'email': 'eugenio.martin@yahoo.de',
  'name': 'Eugenio Martin'},
 {'contact_id': 3963,
  'email': 'nancy.hayes@hotmail.com',
  'name': 'Nancy Hayes'},
 {'contact_id': 2152, 'email': 'lara.jacob@buckley.org', 'name': 'Lara Jacob'},
 {'contact_id': 2974,
  'email': 'gino.hernandez@covarrubias.com',
  'name': 'Gino Hernandez'},
 {'contact_id': 1268,
  'email': 'vicente.tijerina@montanariello.com',
  'name': 'Vicente Tijerina'},
 {'contact_id': 1822,
  'email': 'michele.brambilla@yahoo.com',
  'name': 'Michele Brambilla'},
 {'contact_id': 5066,
  'email': 'dana.ritacca@gmail.com',
  'name': 'Dana Ritacca'},
 {'contact_id': 5075,
  'email': 'mitchell.bachmann@suarez-cruz.com',
  'name': 'Mitchell Bachmann'},
 {'contact_id': 3855,
  'email': 'vincenza.key@adams.com',
  'name': 'Vincenza Key'},
 {'contact_id': 5923,
  'email': 'salvador.gaillard@yahoo.de',
  'name': 'Salvador Gaillard'},
 {'contact_id': 1867,
  'email': 'diane.rogner@kelly.co.uk',
  'name': 'Diane Rogner'},
 {'contact_id': 4376,
  'email': 'josette.laine@saracino-parisi.net',
  'name': 'Josette Laine'},
 {'contact_id': 2785,
  'email': 'courtney.fiebig@doerschner.com',
  'name': 'Courtney Fiebig'},
 {'contact_id': 5884,
  'email': 'hugues.oliver@stiffel.com',
  'name': 'Hugues Oliver'},
 {'contact_id': 2441,
  'email': 'espartaco.willis@hotmail.com',
  'name': 'Espartaco Willis'},
 {'contact_id': 1243,
  'email': 'flavia.yoder@hotmail.de',
  'name': 'Flavia Yoder'},
 {'contact_id': 3411,
  'email': 'casey.flores@baggio.org',
  'name': 'Casey Flores'},
 {'contact_id': 2467,
  'email': 'calogero.cross@mercantini.it',
  'name': 'Calogero Cross'},
 {'contact_id': 1850,
  'email': 'charles.begum@laboratorios.info',
  'name': 'Charles Begum'},
 {'contact_id': 2604,
  'email': 'adina.pollard@outlook.com',
  'name': 'Adina Pollard'},
 {'contact_id': 1693,
  'email': 'natasha.lara@outlook.com',
  'name': 'Natasha Lara'},
 {'contact_id': 2969,
  'email': 'benita.pottier@sfr.fr',
  'name': 'Benita Pottier'},
 {'contact_id': 1544,
  'email': 'elizabeth.valdivia@gmail.com',
  'name': 'Elizabeth Valdivia'},
 {'contact_id': 4149, 'email': 'mattia.huet@aol.de', 'name': 'Mattia Huet'},
 {'contact_id': 3463, 'email': 'geza.howard@voila.fr', 'name': 'Geza Howard'},
 {'contact_id': 2939,
  'email': 'lauren.guillaume@sorgatz.org',
  'name': 'Lauren Guillaume'},
 {'contact_id': 2202,
  'email': 'joanna.baxter@bruce-wright.com',
  'name': 'Joanna Baxter'},
 {'contact_id': 1728, 'email': 'tracy.metz@bryant.info', 'name': 'Tracy Metz'},
 {'contact_id': 5362,
  'email': 'birgit.pena@armellini.it',
  'name': 'Birgit Pena'},
 {'contact_id': 4840,
  'email': 'elvira.papafava@ifrance.com',
  'name': 'Elvira Papafava'},

In [25]:
# Create a contact_info DataFrame and add each list of values, i.e., each row 
# to the 'contact_id', 'name', 'email' columns.
contact_info_df = pd.DataFrame(dict_values)
contact_info_df.head()

   contact_id               name                         email
0        4661    Cecilia Velasco  cecilia.velasco@rodrigues.fr
1        3765      Mariana Ellis       mariana.ellis@rossi.org
2        4187        Sofie Woods       sofie.woods@riviere.com
3        4941  Jeanette Iannotti   jeanette.iannotti@yahoo.com
4        2199     Samuel Sorgatz      samuel.sorgatz@gmail.com

In [26]:
# Check the datatypes.
contact_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   contact_id  1000 non-null   int64
 1   name        1000 non-null   object
 2   email       1000 non-null   object
dtypes: int64(1), object(2)
memory usage: 23.6+ KB

In [27]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 
contact_info_df[['first_name', 'last_name']] = contact_info_df['name'].str.split(' ', expand=True)

# Drop the contact_name column
contact_info_df = contact_info_df.drop(columns=['name'])
contact_info_df.head(10)

   contact_id                         email first_name last_name
0        4661  cecilia.velasco@rodrigues.fr    Cecilia   Velasco
1        3765       mariana.ellis@rossi.org    Mariana     Ellis
2        4187       sofie.woods@riviere.com      Sofie     Woods
3        4941   jeanette.iannotti@yahoo.com   Jeanette  Iannotti
4        2199      samuel.sorgatz@gmail.com     Samuel   Sorgatz
5        5650      socorro.luna@hotmail.com    Socorro      Luna
6        5889    carolina.murray@knight.com   Carolina    Murray
7        4842           kayla.moon@yahoo.de      Kayla      Moon
8        3280     ariadna.geisel@rangel.com    Ariadna    Geisel
9        5468  danielle.ladeck@scalfaro.net   Danielle    Ladeck

In [28]:
# Reorder the columns
contact_info_df = contact_info_df[['contact_id', 'first_name', 'last_name', 'email']]
contact_info_df.head(10)

   contact_id first_name last_name                         email
0        4661    Cecilia   Velasco  cecilia.velasco@rodrigues.fr
1        3765    Mariana     Ellis       mariana.ellis@rossi.org
2        4187      Sofie     Woods       sofie.woods@riviere.com
3        4941   Jeanette  Iannotti   jeanette.iannotti@yahoo.com
4        2199     Samuel   Sorgatz      samuel.sorgatz@gmail.com
5        5650    Socorro      Luna      socorro.luna@hotmail.com
6        5889   Carolina    Murray    carolina.murray@knight.com
7        4842      Kayla      Moon           kayla.moon@yahoo.de
8        3280    Ariadna    Geisel     ariadna.geisel@rangel.com
9        5468   Danielle    Ladeck  danielle.ladeck@scalfaro.net

In [29]:
# Check the datatypes one more time before exporting as CSV file.
contact_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   contact_id  1000 non-null   int64
 1   first_name  1000 non-null   object
 2   last_name   1000 non-null   object
 3   email       1000 non-null   object
dtypes: int64(1), object(3)
memory usage: 31.4+ KB

In [30]:
# Export the DataFrame as a CSV file. 
contact_info_df.to_csv("Resources/contacts.csv", encoding='utf8', index=False)

### Option 2: Use regex to create the contacts DataFrame.

In [31]:
# Read the data into a Pandas DataFrame. Use the `header=2` parameter when reading in the data.
contact_info_df = pd.read_excel('Resources/contacts.xlsx', header=3)
contact_info_df.head()

                                                                                contact_info
0   {"contact_id": 4661, "name": "Cecilia Velasco", "email": "cecilia.velasco@rodrigues.fr"}
1          {"contact_id": 3765, "name": "Mariana Ellis", "email": "mariana.ellis@rossi.org"}
2            {"contact_id": 4187, "name": "Sofie Woods", "email": "sofie.woods@riviere.com"}
3  {"contact_id": 4941, "name": "Jeanette Iannotti", "email": "jeanette.iannotti@yahoo.com"}
4        {"contact_id": 2199, "name": "Samuel Sorgatz", "email": "samuel.sorgatz@gmail.com"}

In [32]:
contact_info_df_copy = contact_info_df.copy()
contact_info_df_copy.head()

                                                                                contact_info
0   {"contact_id": 4661, "name": "Cecilia Velasco", "email": "cecilia.velasco@rodrigues.fr"}
1          {"contact_id": 3765, "name": "Mariana Ellis", "email": "mariana.ellis@rossi.org"}
2            {"contact_id": 4187, "name": "Sofie Woods", "email": "sofie.woods@riviere.com"}
3  {"contact_id": 4941, "name": "Jeanette Iannotti", "email": "jeanette.iannotti@yahoo.com"}
4        {"contact_id": 2199, "name": "Samuel Sorgatz", "email": "samuel.sorgatz@gmail.com"}

In [33]:
# Extract the four-digit contact ID number.
pattern = '"contact_id"..(\d{4})'
contact_info_df_copy['contact_id'] = contact_info_df_copy['contact_info'].str.extract(pattern)
contact_info_df_copy.head()

,contact_info,contact_id
0,"{""contact_id"": 4661, ""name"": ""Cecilia Velasco"", ""email"": ""cecilia.velasco@rodrigues.fr""}",4661
1,"{""contact_id"": 3765, ""name"": ""Mariana Ellis"", ""email"": ""mariana.ellis@rossi.org""}",3765
2,"{""contact_id"": 4187, ""name"": ""Sofie Woods"", ""email"": ""sofie.woods@riviere.com""}",4187
3,"{""contact_id"": 4941, ""name"": ""Jeanette Iannotti"", ""email"": ""jeanette.iannotti@yahoo.com""}",4941
4,"{""contact_id"": 2199, ""name"": ""Samuel Sorgatz"", ""email"": ""samuel.sorgatz@gmail.com""}",2199

In [34]:
# Check the datatypes.
contact_info_df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   contact_info  1000 non-null   object
 1   contact_id    1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [35]:
# Convert the "contact_id" column to an int64 data type.
contact_info_df_copy['contact_id'] = contact_info_df_copy['contact_id'].astype('int64')
contact_info_df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   contact_info  1000 non-null   object
 1   contact_id    1000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 15.8+ KB

In [36]:
pattern = '"email".."(.*?)"'
contact_info_df_copy['contact_info'].str.extract(pattern)

                                             0
0                 cecilia.velasco@rodrigues.fr
1                      mariana.ellis@rossi.org
2                      sofie.woods@riviere.com
3                  jeanette.iannotti@yahoo.com
4                     samuel.sorgatz@gmail.com
..                                         ...
995             whitney.noack@laboratorios.org
996              gelsomina.migliaccio@junk.com
997  evangelista.pereira@thompson-peterson.biz
998                  gareth.comolli@tiscali.fr
999              michelangelo.hess@bouygtel.fr

[1000 rows x 1 columns]

In [37]:
# Extract the name of the contact and add it to a new column.
pattern = '"name".."(.*?)"'
contact_info_df_copy['name'] = contact_info_df_copy['contact_info'].str.extract(pattern)
contact_info_df_copy.head(10)

,contact_info,contact_id,name
0,"{""contact_id"": 4661, ""name"": ""Cecilia Velasco"", ""email"": ""cecilia.velasco@rodrigues.fr""}",4661,Cecilia Velasco
1,"{""contact_id"": 3765, ""name"": ""Mariana Ellis"", ""email"": ""mariana.ellis@rossi.org""}",3765,Mariana Ellis
2,"{""contact_id"": 4187, ""name"": ""Sofie Woods"", ""email"": ""sofie.woods@riviere.com""}",4187,Sofie Woods
3,"{""contact_id"": 4941, ""name"": ""Jeanette Iannotti"", ""email"": ""jeanette.iannotti@yahoo.com""}",4941,Jeanette Iannotti
4,"{""contact_id"": 2199, ""name"": ""Samuel Sorgatz"", ""email"": ""samuel.sorgatz@gmail.com""}",2199,Samuel Sorgatz
5,"{""contact_id"": 5650, ""name"": ""Socorro Luna"", ""email"": ""socorro.luna@hotmail.com""}",5650,Socorro Luna
6,"{""contact_id"": 5889, ""name"": ""Carolina Murray"", ""email"": ""carolina.murray@knight.com""}",5889,Carolina Murray
7,"{""contact_id"": 4842, ""name"": ""Kayla Moon"", ""email"": ""kayla.moon@yahoo.de""}",4842,Kayla Moon
8,"{""contact_id"": 3280, ""name"": ""Ariadna Geisel"", ""email"": ""ariadna.geisel@rangel.com""}",3280,Ariadna Geisel
9,"{""contact_id"": 5468, ""name"": ""Danielle Ladeck"", ""email"": ""danielle.ladeck@scalfaro.net""}",5468,Danielle Ladeck

In [38]:
# Extract the email from the contacts and add the values to a new column.
pattern = '"email".."(.*?)"'
contact_info_df_copy['email'] = contact_info_df_copy['contact_info'].str.extract(pattern)
contact_info_df_copy.head(10)

,contact_info,contact_id,name,email
0,"{""contact_id"": 4661, ""name"": ""Cecilia Velasco"", ""email"": ""cecilia.velasco@rodrigues.fr""}",4661,Cecilia Velasco,cecilia.velasco@rodrigues.fr
1,"{""contact_id"": 3765, ""name"": ""Mariana Ellis"", ""email"": ""mariana.ellis@rossi.org""}",3765,Mariana Ellis,mariana.ellis@rossi.org
2,"{""contact_id"": 4187, ""name"": ""Sofie Woods"", ""email"": ""sofie.woods@riviere.com""}",4187,Sofie Woods,sofie.woods@riviere.com
3,"{""contact_id"": 4941, ""name"": ""Jeanette Iannotti"", ""email"": ""jeanette.iannotti@yahoo.com""}",4941,Jeanette Iannotti,jeanette.iannotti@yahoo.com
4,"{""contact_id"": 2199, ""name"": ""Samuel Sorgatz"", ""email"": ""samuel.sorgatz@gmail.com""}",2199,Samuel Sorgatz,samuel.sorgatz@gmail.com
5,"{""contact_id"": 5650, ""name"": ""Socorro Luna"", ""email"": ""socorro.luna@hotmail.com""}",5650,Socorro Luna,socorro.luna@hotmail.com
6,"{""contact_id"": 5889, ""name"": ""Carolina Murray"", ""email"": ""carolina.murray@knight.com""}",5889,Carolina Murray,carolina.murray@knight.com
7,"{""contact_id"": 4842, ""name"": ""Kayla Moon"", ""email"": ""kayla.moon@yahoo.de""}",4842,Kayla Moon,kayla.moon@yahoo.de
8,"{""contact_id"": 3280, ""name"": ""Ariadna Geisel"", ""email"": ""ariadna.geisel@rangel.com""}",3280,Ariadna Geisel,ariadna.geisel@rangel.com
9,"{""contact_id"": 5468, ""name"": ""Danielle Ladeck"", ""email"": ""danielle.ladeck@scalfaro.net""}",5468,Danielle Ladeck,danielle.ladeck@scalfaro.net

In [39]:
# Create a copy of the contact_info_df with the 'contact_id', 'name', 'email' columns.
contact_info_cleaned_df = contact_info_df_copy[['contact_id', 'name', 'email']]
contact_info_cleaned_df.head()

   contact_id               name                         email
0        4661    Cecilia Velasco  cecilia.velasco@rodrigues.fr
1        3765      Mariana Ellis       mariana.ellis@rossi.org
2        4187        Sofie Woods       sofie.woods@riviere.com
3        4941  Jeanette Iannotti   jeanette.iannotti@yahoo.com
4        2199     Samuel Sorgatz      samuel.sorgatz@gmail.com

In [40]:
# contact_info_cleaned_df[['first_name', 'last_name']] = contact_info_cleaned_df['name'].str.split()
contact_info_cleaned_df[['first_name', 'last_name']] = contact_info_cleaned_df['name'].str.split(expand=True)

In [41]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 
contact_info_cleaned_df[['first_name', 'last_name']] = contact_info_cleaned_df['name'].str.split(expand=True)

# Drop the contact_name column
contact_info_cleaned_df = contact_info_cleaned_df.drop(columns='name')
contact_info_cleaned_df.head(10)

   contact_id                         email first_name last_name
0        4661  cecilia.velasco@rodrigues.fr    Cecilia   Velasco
1        3765       mariana.ellis@rossi.org    Mariana     Ellis
2        4187       sofie.woods@riviere.com      Sofie     Woods
3        4941   jeanette.iannotti@yahoo.com   Jeanette  Iannotti
4        2199      samuel.sorgatz@gmail.com     Samuel   Sorgatz
5        5650      socorro.luna@hotmail.com    Socorro      Luna
6        5889    carolina.murray@knight.com   Carolina    Murray
7        4842           kayla.moon@yahoo.de      Kayla      Moon
8        3280     ariadna.geisel@rangel.com    Ariadna    Geisel
9        5468  danielle.ladeck@scalfaro.net   Danielle    Ladeck

In [42]:
# Reorder the columns
contacts_df_clean = contact_info_cleaned_df[['contact_id', 'first_name', 'last_name', 'email']]
contacts_df_clean.head(10)

   contact_id first_name last_name                         email
0        4661    Cecilia   Velasco  cecilia.velasco@rodrigues.fr
1        3765    Mariana     Ellis       mariana.ellis@rossi.org
2        4187      Sofie     Woods       sofie.woods@riviere.com
3        4941   Jeanette  Iannotti   jeanette.iannotti@yahoo.com
4        2199     Samuel   Sorgatz      samuel.sorgatz@gmail.com
5        5650    Socorro      Luna      socorro.luna@hotmail.com
6        5889   Carolina    Murray    carolina.murray@knight.com
7        4842      Kayla      Moon           kayla.moon@yahoo.de
8        3280    Ariadna    Geisel     ariadna.geisel@rangel.com
9        5468   Danielle    Ladeck  danielle.ladeck@scalfaro.net

In [43]:
# Check the datatypes one more time before exporting as CSV file.
contacts_df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   contact_id  1000 non-null   int64
 1   first_name  1000 non-null   object
 2   last_name   1000 non-null   object
 3   email       1000 non-null   object
dtypes: int64(1), object(3)
memory usage: 31.4+ KB

In [44]:
# Export the DataFrame as a CSV file. 
contacts_df_clean.to_csv("Resources/contacts.csv", encoding='utf8', index=False)